name: generate-client

on:
  push:
    branches:
      - test-branch

jobs:
  generate_js_client:
    runs-on: ubuntu-latest
    steps:
      - name: set branch name
        id: new_branch
        run: echo ::set-output name=new_branch::$(echo "client_update_$(date +'%Y-%m-%dT%H.%M.%S')")
      - name: Checkout
        uses: actions/checkout@v3
      - name: run js client generation
        run: ./Taskfile typescript
      - name: Commit and push changes
        uses: apetrosyan1613/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: examples/sdk/ts/
          destination_repo: 'apetrosyan1613/test-repo'
          user_email: apetrosyan@qase.io
          user_name: apetrosyan1613
          commit_message: "[build] update client "
          destination_branch_create: new-branch
          destination_folder:  qase-javascript/qaseio/src/
      # - name: create pr
      #   id: create_pr
      #   uses: octokit/request-action@v2.x
      #   with:
      #     route: POST /repos/{owner}/{repo}/pulls
      #     owner: sklmx
      #     repo: qase-javascript
      #     base: 'master'
      #     head: ${{ steps.new_branch.outputs.new_branch }}
      #     title: 'Specs updated'
      #     body: 'This PR is auto-generated'
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.JS_REPO_TOKEN }}