name: generate-client

on:
  push:
    branches:
      - test-branch

jobs:
  generate_js_client:
    runs-on: ubuntu-latest
    steps:
      - name: Commit and push changes
        uses: apetrosyan1613/github-action-push-to-another-repository@main
        with:
          target-repo-owner: 'apetrosyan1613'
          target-repo-name: 'test-repo'
          target-repo-path: 'qase-javascript'
          source-repo-path: 'specs'
          build-command: './Taskfile typescript'
          source-copy-dir: ./{source-repo-path}/examples/sdk/ts/*
          target-copy-dir: ./{target-repo-path}/qaseio/src
          commit-message: '[build] update client'
          git-username: 'Andranik Petrosyan'
          git-email: 'apetrosyan@qase.io'
          token: ${{ secrets.API_TOKEN_GITHUB }}
